import React, { useState, useContext } from "react";
import Head from "next/head";
import FavoritesContext from "../context/allContext";
import Navbar from "../components/client/Navbar";
import { XIcon } from "@heroicons/react/solid";
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

export default function Home() {
  const userCtx = useContext(FavoritesContext);
  const [authUser, setAuthUser] = useState(userCtx.approvedChecked);
  // const imgref = useRef();
  // const [ProductImage, setProductImage] = useState(null);

  const [uploadStatus, setUploadStatus] = useState(false);
  return (
    <div>
      <Head>
        <title>Nepal app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex justify-center mt-8">
        <div>
          <div className="flex">
            <h1 className="mb-4 font-bold text-xl text-slate-800 mr-4">
              Status for your Application
            </h1>
            {authUser.length !== 0 ? (
              <p className="font-semibold text-lg mt-1 text-green-700">
                Approved
              </p>
            ) : (
              <p className="font-semibold text-lg mt-1 text-red-500">Pending</p>
            )}
          </div>
          <div className={`mt-8`}>
            {/* <label htmlFor="formFile" className="form-label">
                  Image count should not exceed 10
                </label> */}
            <div
              className={`flex justify-between bg-green-300 h-10 rounded py-2 px-2 ${
                uploadStatus ? `block` : `hidden`
              } `}
            >
              <h1 className="font-medium text-base text-slate-700">
                File uploaded
              </h1>
              <XIcon
                className="h-6 w-6 text-slate-700"
                onClick={() => setUploadStatus(false)}
              />
            </div>
            <h1 className="mb-4 font-bold text-xl text-slate-800">
              Upload Document
            </h1>
            <div className="flex">
              <input
                className="form-control"
                type="file"
                id="formFile"
                // onChange={(e) => setProductImage(e.target.files[0])}
              />
              <a
                href="#"
                className="w-24 flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 md:py-1 md:text-base md:px-10"
                onClick={() => setUploadStatus(true)}
              >
                Upload
              </a>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
